service: serverless-framework-custom-template

frameworkVersion: "3"

provider:
  name: aws
  runtime: nodejs16.x

functions:
  hello:
    handler: src/handler.hello

custom:
  prune:
    automatic: true
    number: 2

plugins:
  - serverless-plugin-typescript
  - serverless-prune-plugin
